version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: info
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: myapp
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: # nginxを基準にcontainerとネットワーク共有
      nginx_default:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 4000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: db@akiumi.net
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks: # nginxを基準にcontainerとネットワーク共有
      nginx_default:

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local

networks:
  nginx_default:
    external: true
